server:
  port: 14000

spring:
  application:
  name: gateway-server
  cloud:
    gateway:
      globalcors: #设置全局跨域处理
        corsConfigurations:
          '[/**]':
          allowedOriginPatterns: "*"
          allowedHeaders: "*"
          allowedMethods: "*"
          allowCredentials: true
          maxAge: 3600
      routes: #设置路由
        - id: user_server
          url: lb://user-server
          predicates:
              - Path=/user/**
        - id: food_server
          url: lb://food-server
          predicates:
              - Path=/food/**
        - id: business_server
          url: lb://business-server
          predicates:
              - Path=/business/**
        - id: cart_server
          url: lb://cart-server
          predicates:
              - Path=/cart/**
        - id: deliveryaddress_server
          url: lb://deliveryaddress-server
          predicates:
              - Path=/deliveryaddress/**
        - id: order_server
          url: lb://order-server
          predicates:
              - Path=/order/**
    sentinel:
      transport:
        dashboard: localhost:8089

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:13000/eureka
  instance:
    prefer-ip-address: true #使用ip地址向Eureka注册
    instance-id: ${spring.cloud.client.ip-address}:${server.port} #自定义微服务实例ID
    lease-renewal-interval-in-seconds: 5 #续约间隔时间
    lease-expiration-duration-in-seconds: 15 #续约到期时间